-- Seed and align dictionaries used by fixed dropdowns across CRM pages.

INSERT INTO sys_dict_type (dict_code, dict_name, dict_type, description, sort_order, status, deleted)
VALUES
('customer_type', '客户类型', 'business', '客户主数据客户类型', 10, 1, 0),
('customer_status', '客户状态', 'business', '客户主数据状态', 11, 1, 0),
('customer_level', '客户等级', 'business', '客户主数据等级', 12, 1, 0),
('biz_type', '业务类型', 'business', '客户业务类型', 13, 1, 0),
('customer_category', '客户分类', 'business', '客户分类', 14, 1, 0),
('customer_source', '客户来源', 'business', '客户来源', 15, 1, 0),
('customer_group', '主要客户群体', 'business', '客户主要客户群体', 16, 1, 0),
('customer_stage', '客户阶段', 'business', '客户生命周期阶段', 17, 1, 0),
('asset_type', '资产类型', 'business', '客户资产类型', 18, 1, 0),
('yes_no', '是否', 'system', '通用是否选项', 19, 1, 0),
('risk_level', '风险等级', 'business', '客户风险等级', 20, 1, 0),
('contact_role', '联系人角色', 'business', '客户联系人角色类型', 21, 1, 0),
('contact_decision_level', '决策层级', 'business', '联系人决策层级', 22, 1, 0),
('contact_status', '联系人状态', 'business', '联系人在职状态', 23, 1, 0),
('address_type', '地址类型', 'business', '客户地址类型', 24, 1, 0),
('transfer_status', '转移状态', 'business', '客户转移状态', 25, 1, 0),
('visit_type', '拜访类型', 'business', '勤力度拜访类型', 30, 1, 0),
('daily_report_parse_status', '日报解析状态', 'business', 'AI日报解析状态', 31, 1, 0),
('wecom_parse_status', '企微解析状态', 'business', '企微消息解析状态', 32, 1, 0),
('performance_grade', '勤力度等级', 'business', '勤力度评分等级', 33, 1, 0),
('lead_type', '线索类型', 'business', '线索与商情类型', 40, 1, 0),
('lead_status', '线索状态', 'business', '线索处理状态', 41, 1, 0),
('lead_source', '线索来源', 'business', '线索来源', 42, 1, 0),
('opportunity_stage', '商机阶段', 'business', '商机推进阶段', 43, 1, 0),
('lost_type', '丢单原因', 'business', '丢单原因类型', 44, 1, 0),
('recovery_possible', '挽回可能', 'business', '丢单挽回可能性', 45, 1, 0),
('quote_status', '报价状态', 'business', '报价单状态', 50, 1, 0),
('target_metric_type', '目标指标类型', 'business', '目标管理指标类型', 51, 1, 0),
('user_status', '用户状态', 'system', '系统用户状态', 60, 1, 0),
('data_scope', '数据权限范围', 'system', '角色数据权限范围', 61, 1, 0),
('dict_status', '字典状态', 'system', '字典启禁用状态', 62, 1, 0),
('dict_type_category', '字典类型类别', 'system', '字典类型类别', 63, 1, 0),
('dict_color', '字典颜色', 'system', '字典标签颜色', 64, 1, 0),
('config_type', '配置值类型', 'system', '系统配置值类型', 65, 1, 0),
('module_record_status', '业务台账状态', 'business', '配置化业务台账状态', 70, 1, 0),
('ai_protocol', 'AI协议类型', 'system', 'AI接口协议类型', 80, 1, 0)
ON CONFLICT (dict_code) DO UPDATE
SET dict_name = EXCLUDED.dict_name,
    dict_type = EXCLUDED.dict_type,
    description = EXCLUDED.description,
    sort_order = EXCLUDED.sort_order,
    status = 1,
    deleted = 0;

WITH seed(dict_code, item_code, item_name, item_value, sort_order, color) AS (
    VALUES
    ('customer_type', '1', '直接客户', '1', 1, 'primary'),
    ('customer_type', '2', '代理', '2', 2, 'warning'),
    ('customer_type', '3', '终端品牌', '3', 3, 'success'),
    ('customer_status', '1', '潜在客户', '1', 1, 'info'),
    ('customer_status', '2', '活跃客户', '2', 2, 'success'),
    ('customer_status', '3', '非活跃', '3', 3, 'warning'),
    ('customer_status', '4', '流失', '4', 4, 'danger'),
    ('customer_status', '5', '新客户', '5', 5, 'primary'),
    ('customer_status', '6', '重点客户', '6', 6, 'success'),
    ('customer_level', '1', 'AAA', '1', 1, 'success'),
    ('customer_level', '2', 'AA', '2', 2, 'success'),
    ('customer_level', '3', 'A', '3', 3, 'primary'),
    ('customer_level', '4', 'B', '4', 4, 'warning'),
    ('customer_level', '5', 'C', '5', 5, 'info'),
    ('biz_type', '1', '内销', '1', 1, 'primary'),
    ('biz_type', '2', '外销', '2', 2, 'success'),
    ('biz_type', '3', '转口', '3', 3, 'warning'),
    ('customer_category', '1', '纱线厂', '1', 1, 'primary'),
    ('customer_category', '2', '面料厂', '2', 2, 'success'),
    ('customer_category', '3', '服装厂', '3', 3, 'warning'),
    ('customer_category', '4', '贸易商', '4', 4, 'info'),
    ('customer_category', '5', '品牌商', '5', 5, 'success'),
    ('customer_source', '1', '展会', '1', 1, 'primary'),
    ('customer_source', '2', '转介绍', '2', 2, 'success'),
    ('customer_source', '3', '自主开发', '3', 3, 'warning'),
    ('customer_source', '4', '平台', '4', 4, 'info'),
    ('customer_group', '1', '外销', '1', 1, 'success'),
    ('customer_group', '2', '内销流通', '2', 2, 'primary'),
    ('customer_group', '3', '电商', '3', 3, 'warning'),
    ('customer_stage', '1', '初期接触', '1', 1, 'info'),
    ('customer_stage', '2', '意向阶段', '2', 2, 'primary'),
    ('customer_stage', '3', '谈判阶段', '3', 3, 'warning'),
    ('customer_stage', '4', '成交客户', '4', 4, 'success'),
    ('customer_stage', '5', '已流失', '5', 5, 'danger'),
    ('asset_type', '1', '国有企业', '1', 1, 'primary'),
    ('asset_type', '2', '民营企业', '2', 2, 'success'),
    ('asset_type', '3', '外资企业', '3', 3, 'warning'),
    ('asset_type', '4', '合资企业', '4', 4, 'info'),
    ('yes_no', '1', '是', '1', 1, 'success'),
    ('yes_no', '0', '否', '0', 2, 'info'),
    ('risk_level', '1', '高风险', '1', 1, 'danger'),
    ('risk_level', '2', '中风险', '2', 2, 'warning'),
    ('risk_level', '3', '低风险', '3', 3, 'success'),
    ('risk_level', '4', '无风险', '4', 4, 'info'),
    ('contact_role', '1', '老板', '1', 1, 'danger'),
    ('contact_role', '2', '采购', '2', 2, 'primary'),
    ('contact_role', '3', '营业', '3', 3, 'success'),
    ('contact_role', '4', '开发', '4', 4, 'warning'),
    ('contact_role', '5', '生产', '5', 5, 'info'),
    ('contact_role', '6', '财务', '6', 6, 'primary'),
    ('contact_role', '7', '品质', '7', 7, 'success'),
    ('contact_decision_level', '1', '拍板', '1', 1, 'danger'),
    ('contact_decision_level', '2', '否决', '2', 2, 'warning'),
    ('contact_decision_level', '3', '参与', '3', 3, 'primary'),
    ('contact_decision_level', '4', '知情', '4', 4, 'info'),
    ('contact_status', '1', '在职', '1', 1, 'success'),
    ('contact_status', '0', '离职', '0', 2, 'info'),
    ('address_type', '1', '注册地', '1', 1, 'primary'),
    ('address_type', '2', '工厂', '2', 2, 'success'),
    ('address_type', '3', '办事处', '3', 3, 'warning'),
    ('address_type', '4', '仓库', '4', 4, 'info'),
    ('address_type', '5', '收货地址', '5', 5, 'success'),
    ('address_type', '9', '其他', '9', 9, 'info'),
    ('transfer_status', '1', '待确认', '1', 1, 'warning'),
    ('transfer_status', '2', '已确认', '2', 2, 'primary'),
    ('transfer_status', '3', '已完成', '3', 3, 'success'),
    ('visit_type', '1', '上门拜访', '1', 1, 'primary'),
    ('visit_type', '2', '电话拜访', '2', 2, 'success'),
    ('visit_type', '3', '微信拜访', '3', 3, 'warning'),
    ('visit_type', '4', '展会', '4', 4, 'info'),
    ('daily_report_parse_status', '0', '未解析', '0', 1, 'info'),
    ('daily_report_parse_status', '1', '解析中', '1', 2, 'warning'),
    ('daily_report_parse_status', '2', '成功', '2', 3, 'success'),
    ('daily_report_parse_status', '3', '失败', '3', 4, 'danger'),
    ('wecom_parse_status', '0', '未处理', '0', 1, 'info'),
    ('wecom_parse_status', '1', '已解析', '1', 2, 'success'),
    ('wecom_parse_status', '2', '解析失败', '2', 3, 'danger'),
    ('performance_grade', '1', 'G', '1', 1, 'success'),
    ('performance_grade', '2', 'C', '2', 2, 'warning'),
    ('performance_grade', '3', 'O', '3', 3, 'danger'),
    ('lead_type', '1', '商情', '1', 1, 'primary'),
    ('lead_type', '2', '线索', '2', 2, 'success'),
    ('lead_status', '1', '新线索', '1', 1, 'info'),
    ('lead_status', '2', '跟进中', '2', 2, 'warning'),
    ('lead_status', '3', '已转化', '3', 3, 'success'),
    ('lead_status', '4', '无效', '4', 4, 'danger'),
    ('lead_source', '1', '日报AI', '1', 1, 'success'),
    ('lead_source', '2', '展会', '2', 2, 'primary'),
    ('lead_source', '3', '主动开发', '3', 3, 'warning'),
    ('lead_source', '4', '转介绍', '4', 4, 'info'),
    ('opportunity_stage', '1', '初步接触', '1', 1, 'info'),
    ('opportunity_stage', '2', '需求确认', '2', 2, 'primary'),
    ('opportunity_stage', '3', '方案报价', '3', 3, 'warning'),
    ('opportunity_stage', '4', '合同谈判', '4', 4, 'danger'),
    ('opportunity_stage', '5', '成交', '5', 5, 'success'),
    ('lost_type', '1', '价格', '1', 1, 'danger'),
    ('lost_type', '2', '交期', '2', 2, 'warning'),
    ('lost_type', '3', '质量', '3', 3, 'danger'),
    ('lost_type', '4', '现货', '4', 4, 'info'),
    ('lost_type', '5', '其他', '5', 5, 'info'),
    ('recovery_possible', '1', '可能', '1', 1, 'warning'),
    ('recovery_possible', '2', '不可能', '2', 2, 'danger'),
    ('quote_status', '1', '草稿', '1', 1, 'info'),
    ('quote_status', '2', '已提交', '2', 2, 'warning'),
    ('quote_status', '3', '已确认', '3', 3, 'success'),
    ('quote_status', '4', '已拒绝', '4', 4, 'danger'),
    ('target_metric_type', '1', '销售额', '1', 1, 'primary'),
    ('target_metric_type', '2', '毛利', '2', 2, 'success'),
    ('target_metric_type', '3', '客户数', '3', 3, 'warning'),
    ('target_metric_type', '4', '拜访次数', '4', 4, 'info'),
    ('user_status', '1', '启用', '1', 1, 'success'),
    ('user_status', '2', '停用', '2', 2, 'info'),
    ('data_scope', '1', '全部数据', '1', 1, 'danger'),
    ('data_scope', '2', '本部门及下级', '2', 2, 'warning'),
    ('data_scope', '3', '本部门', '3', 3, 'primary'),
    ('data_scope', '4', '仅本人', '4', 4, 'info'),
    ('dict_status', '0', '禁用', '0', 1, 'info'),
    ('dict_status', '1', '启用', '1', 2, 'success'),
    ('dict_type_category', 'SYSTEM', '系统', 'SYSTEM', 1, 'primary'),
    ('dict_type_category', 'CUSTOM', '自定义', 'CUSTOM', 2, 'success'),
    ('dict_color', 'primary', 'primary', 'primary', 1, 'primary'),
    ('dict_color', 'success', 'success', 'success', 2, 'success'),
    ('dict_color', 'warning', 'warning', 'warning', 3, 'warning'),
    ('dict_color', 'danger', 'danger', 'danger', 4, 'danger'),
    ('dict_color', 'info', 'info', 'info', 5, 'info'),
    ('config_type', 'STRING', '字符串', 'STRING', 1, 'primary'),
    ('config_type', 'INT', '整数', 'INT', 2, 'success'),
    ('config_type', 'FLOAT', '小数', 'FLOAT', 3, 'warning'),
    ('config_type', 'BOOLEAN', '布尔', 'BOOLEAN', 4, 'info'),
    ('config_type', 'JSON', 'JSON', 'JSON', 5, 'primary'),
    ('module_record_status', 'DRAFT', '草稿', 'DRAFT', 1, 'info'),
    ('module_record_status', 'ACTIVE', '进行中', 'ACTIVE', 2, 'warning'),
    ('module_record_status', 'DONE', '已完成', 'DONE', 3, 'success'),
    ('ai_protocol', 'OPENAI_CHAT', 'OpenAI兼容', 'OPENAI_CHAT', 1, 'primary'),
    ('ai_protocol', 'ANTHROPIC_MESSAGES', 'Claude Messages', 'ANTHROPIC_MESSAGES', 2, 'success')
)
INSERT INTO sys_dict_item (dict_id, item_code, item_name, item_value, sort_order, color, status, deleted)
SELECT t.id, s.item_code, s.item_name, s.item_value, s.sort_order, s.color, 1, 0
FROM seed s
JOIN sys_dict_type t ON t.dict_code = s.dict_code
ON CONFLICT (dict_id, item_code) DO UPDATE
SET item_name = EXCLUDED.item_name,
    item_value = EXCLUDED.item_value,
    sort_order = EXCLUDED.sort_order,
    color = EXCLUDED.color,
    status = 1,
    deleted = 0;
