package com.huafu.crm.customer.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.math.BigDecimal;

public record CustomerCreateDTO(
    String customerCode,  // 非必填，后端自动生成
    @NotBlank @Size(max = 255, message = "客户名称不能超过255个字符") String customerName,
    String customerShortName,
    @NotNull Integer type,
    Integer level,
    Integer status,
    String province,
    String city,
    String district,
    String address,
    String mainContactName,
    String mainContactPhone,
    String mainContactRole,
    BigDecimal annualRevenue,
    BigDecimal creditLimit,
    BigDecimal taxRate,
    Integer paymentDays,
    String sapCustomerCode,
    String remark,
    Long ownerUserId,
    // === P0 扩展字段 ===
    String customerCategory,
    String customerSegment,
    Integer businessType,
    String countryRegion,
    String mainBrand,
    BigDecimal annualYarnVolume,
    Integer machineCount,
    String productionCapacity,
    String industryPosition,
    String mainCustomerGroup,
    String bundleCustomerName,
    String bundleBrand,
    Long ownerDeptId,
    String salesMerchandiser,
    BigDecimal locationLat,
    BigDecimal locationLng,
    String unifiedSocialCreditCode,
    String englishName,
    String assetType,
    String customerSource,
    Integer customerStage,
    String competitorShareJson,
    String cooperationBrandJson,
    Integer blacklist,
    Integer riskLevel,
    String taxId,
    String bankName,
    String bankAccount,
    String invoiceTitle,
    String companyCode,
    String salesGroup,
    String priceList,
    String currency,
    String deliveryFactory,
    String accountAssignmentGroup,
    String taxClassification,
    String shipToParty,
    String soldToParty,
    String payerParty,
    String countryCode,
    String region
) {}
